// Route path constants
export const ROUTES = {
    LANDING: '/',
    LOGIN: '/claim-workshop-login',
    CLAIM_WORKSHOP_LOGIN: '/claim-workshop-login',
    CLAIM_SURVEYOR_LOGIN: '/claim-surveyor-login',
    CLAIM_WEBLINK: '/claim-weblink',
    PREINSPECTION_AGENT_LOGIN: '/preinspection-agent-login',
    PREINSPECTION_SURVEYOR_LOGIN: '/preinspection-surveyor-login',
    PREINSPECTION_WEBLINK: '/preinspection-weblink',
    DASHBOARD: '/dashboard',
    CLAIM_START: '/claim-start',
    OWNER_VEHICLE_DETAILS: '/owner-vehicle-details',
    DOCUMENT_UPLOAD: '/document-upload',
    INSPECTION_DETAILS: '/inspection-details',
    PHOTO_CAPTURE_SELECTION: '/photo-capture-selection',
    CAMERA_CAPTURE: '/camera-capture/:angle',
    ADD_DAMAGE_PHOTOS: '/add-damage-photos',
    DAMAGE_REVIEW: '/damage-review',
    SUBMITTED: '/submitted',
    REINSPECTION_PHOTOS: '/reinspection-photos',
    REPAIR_SUBMISSION: '/repair-submission',
    VEHICLE_INFORMATION: '/vehicle-information',
};
